"""Update tournaments table schema

Revision ID: 5be317bbeb41
Revises: e30f62179756
Create Date: 2026-04-02 16:15:27.304452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be317bbeb41'
down_revision = 'e30f62179756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('logo_data', sa.LargeBinary(), nullable=True))
    op.add_column('tournaments', sa.Column('logo_content_type', sa.String(length=50), nullable=True))
    op.drop_column('tournaments', 'logo_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('logo_url', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('tournaments', 'logo_content_type')
    op.drop_column('tournaments', 'logo_data')
    # ### end Alembic commands ###
