"""Add created_at field to players table

Revision ID: 9d24cd7a5a87
Revises: 5be317bbeb41
Create Date: 2026-04-02 16:55:08.245903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d24cd7a5a87'
down_revision = '5be317bbeb41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'created_at')
    # ### end Alembic commands ###
